openscad -D "teeth=8;clearance=-0.2;extra_adjust_axle=-0.06;printer=""bambu""" -o ../stl/gear/gear-08-bambu.stl gear.scad
openscad -D "teeth=12;extra_adjust_axle=0.0;printer=""bambu""" -o ../stl/gear/gear-12-bambu.stl gear.scad
openscad -D "teeth=16;extra_adjust_axle=0.03;printer=""bambu""" -o ../stl/gear/gear-16-bambu.stl gear.scad
openscad -D "teeth=20;printer=""bambu""" -o ../stl/gear/gear-20-bambu.stl gear.scad
openscad -D "teeth=24;extra_adjust_axle=0.03;printer=""bambu""" -o ../stl/gear/gear-24-bambu.stl gear.scad
openscad -D "teeth=28;printer=""bambu""" -o ../stl/gear/gear-28-bambu.stl gear.scad
openscad -D "teeth=32;printer=""bambu""" -o ../stl/gear/gear-32-bambu.stl gear.scad
openscad -D "teeth=36;printer=""bambu""" -o ../stl/gear/gear-36-bambu.stl gear.scad
openscad -D "teeth=40;printer=""bambu""" -o ../stl/gear/gear-40-bambu.stl gear.scad